version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - blockchain-net

  backend:
    build:
      context: ./backend
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./backend:/app
      - ./.env:/app/.env  # .envファイルをコンテナ内にマウント
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - BITCOIN_API_URL=${BITCOIN_API_URL}
      - ETHEREUM_API_URL=${ETHEREUM_API_URL}
      - BLOCKCYPHER_API_KEY=${BLOCKCYPHER_API_KEY}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - DEBUG=${DEBUG:-False}
      - CORS_ORIGINS=${CORS_ORIGINS}
    depends_on:
      - db
    networks:
      - blockchain-net

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - blockchain-net

volumes:
  postgres_data:

networks:
  blockchain-net:
    driver: bridge
